### ISSUE TITLE
Question: Tool to easier use AutoEq Correction Data

### ISSUE THREAD

**Issue by Ebert-Hanke** [moode-player/moode#492]
As a user of moOde and mostly headphone listener I started working on a little hobby project to make it easier for me to create config files for CamillaDSP using correction data from [AutoEq](https://github.com/jaakkopasanen/AutoEq). Since I prefer ParamEQ for the moment to Impulse response `.wav` this makes it easier if one owns several Headphones / IEMs. Still very early stages but maybe it can be useful for someone or could even be integrated into moOde in some way at some point (?)
So if this seems useful to pursue also for other users, I would try to put more work into it.
This is it: [autoeq2camilladsp](https://github.com/Ebert-Hanke/autoeq2camilladsp)

What is not clear to me is how much of the CamillaDSP config, specifically the `devices` section is actually used by moOde or which parts are replaced with config data from the moOde config. Maybe someone could clarify this for me. Thanks!

Also: I really enjoy moOde! Thanks for all the work on it!

**Comment by moodeaudio** [comment]
What config data are you referring to?
```
...which parts are replaced with config data from the moOde config.
```

**Comment by Ebert-Hanke** [comment]
Sorry I was not very clear. In a CamillaDSP config is the `devices` section which configures the hardware, eg:
```
devices:
  samplerate: 96000
  chunksize: 1024
  queuelimit: 4 (*)
  silence_threshold: -60 (*)
  silence_timeout: 3.0 (*)
  target_level: 500 (*)
  adjust_period: 10 (*)
  enable_rate_adjust: true (*)
  enable_resampling: true (*)
  resampler_type: BalancedAsync (*)
  capture_samplerate: 44100 (*)
  stop_on_rate_change: false (*)
  rate_measure_interval: 1.0 (*)
  capture:
    type: Pulse
    channels: 2
    device: "MySink.monitor"
    format: S16LE
  playback:
    type: Alsa
    channels: 2
    device: "hw:Generic_1"
    format: S32LE
```
Since one configures some of these things in moOde I was assuming the config of moOde will take priority over any (or some) values in there. I am just not sure how CamillaDSP is implemented in moOde and I think I have read in a forum that parts of the `devices` section are ignored / overwritten with configuration from moOde.
